#!/bin/sh

cd ~/.config/

git submodule init
git submodule update
if [ ! -L nvim/lua/custom ]; then
    ln -s ../../nvim_custom nvim/lua/custom
fi

if [ -f ../.bashrc ] && [ ! -L ../.bashrc ] || [ "$(readlink ../.bashrc)" != ".config/bash/bashrc" ]; then
    mv ../.bashrc ../.bashrc.bak
fi
if [ ! -L ../.bashrc ]; then
    ln -s .config/bash/bashrc ../.bashrc
fi

# Check current global git user name
current_name=$(git config --global user.name)
if [ -n "$current_name" ]; then
  echo "Git user.name is already set to: $current_name"
else
  read -p "Enter your Git name: " git_name
  git config -f ../.gitconfig user.name "$git_name"
fi

# Check current global git user email
current_email=$(git config --global user.email)
if [ -n "$current_email" ]; then
  echo "Git user.email is already set to: $current_email"
else
  read -p "Enter your Git email: " git_email
  git config -f ../.gitconfig user.email "$git_email"
fi

# Confirm current values
echo "Final Git global config:"
git config --global --get user.name
git config --global --get user.email
