# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = sleep 3; uwsm-app -- 1password --silent
# exec-once = uwsm-app -- 1password.desktop
# exec-once = sh -c 'until busctl --user --list | grep -q org.kde.StatusNotifierWatcher; do sleep 0.25; done; uwsm-app -- 1password --silent'
exec-once = ~/.config/hypr/scripts/restart-waybar-on-reload.sh
